### ISSUE TITLE
Conceding the game / match

### ISSUE THREAD

**Issue by fbatista** [Juizes-MTG-Portugal/Juizes-MTG-Portugal.github.io#17]
Currently the policy for conceding at instant speed looks like this:

> 2.5B. If a player leaving the game would affect current or imminent game actions, those actions occur as though that player was still in the game until the end of the current phase.

However, this makes strategies that depend on multiple turns or combat phases vulnerable to an arranged concession deal in order to potentially kingmake a player in order to force a draw. It's an edge case but it can definitely be something that can happen in high level play.

Since we want to avoid this behavioral pattern (of using concession to suicide to remove a win from a player, and undermining certain strategies), we should not allow this.

The ruleset used widely in the US:

> MTRA 2.5
During a multiplayer game players are encouraged to concede while they have priority and the stack is empty on their own turn. A player who needs to concede at any other time will be dropped from the event and must talk to a tournament organizer in order to re-enter. In this case a judge will facilitate any mandatory actions of the conceded player until the stack is empty. In the event this happens in response to combat the turn will be facilitated until the end of combat.

Tackles this problem by forcing a player that is conceding at instant speed to drop from the event. Which removes the potential for this strategy. However, it's not clear that this heavy handed solution, is the best, and also, there is the option to "talk to a tournament organizer in order to re-enter", which is unclear on what the conditions are to re-enter the event, putting responsibility on the tournament organizer instead of the rules. Since the rules exist to protect EVERYONE at a tournament, including the organizer, it's best if the rules are clear and explicit as much as possible.

---
## Proposal

~So we need to figure out a solution for this, perhaps we still go with the drop solution, or we simply penalize the player that concedes at instant speed with a Match Loss.~

~Maybe conceding at instant speed is an Unsporting Conduct - Major? -- It shouldn't be an infraction, because conceding on purpose is something we want to allow, for players to be able to remove themselves from an uncomfortable situation, without the risk of purposefully breaking a rule! However in order to avoid potential for abuse, we need to treat the instant-speed concession as a match loss.~

~With this, there can still be the case for Collusion between 3 players, handing over the win to the surviving one, but then that's handled as Collusion, and it would be a Disqualification.~

### Under Discussion below!

Related issue: https://github.com/Juizes-MTG-Portugal/Juizes-MTG-Portugal.github.io/issues/1

**Comment by purplejudge** [comment]
I very much dislike treating conceding as a Match Loss at a base level. Philosophically, it just does not make sense. We can talk about doing it with ill intent and getting into collusion situations, but the base mindset behind conceding cannot be that it is a very negative thing. By saying it is Unsporting Conduct - Major to concede at instant speed, we are saying it is as bad as, for example: A player using a racial slur against their opponent or a player taking inappropriate photos of another player without express permission (all examples from the IPG btw). If a player calls us and says "Listen, my wife is giving birth, I need to leave RIGHT NOW" or "I'm not feeling well, I need to go to the bathroom RIGHT NOW", does it make sense to say "All right, but what you are doing is as bad as if you had just called that person over there the n-word, so I'm giving you a Match Loss for Unsporting Conduct - Major"? No, absolutely not.

In fact, philosophically, and unless we change the policy to reflect this, it shouldn't be ANY sort of penalty. The policy says "encourage", not "mandates". I agree with this wording, conceding has to be a rightly-available right for any player.

Also, notice how our fix is already better than the one used in the US: we always help the players navigate to the end of the phase. This will always have to include an empty stack at some point, even if it's just at the end of said phase. The US fix only waits for the stack to be empty, which will always take less time than the help we provide with our fix.

I like the fix we have as it represents a compromise between players and tournament officials: you want this player to stay until the end, but we have to let them go. We can't have a judge sit here and play out the rest of the match because it would be a logistical strain and the skill of the judge as a player would start to factor in much more. On top of that, the player also needs to take their cards with them! It just isn't feasible, sorry.

I think you answered your own question with the question itself:

Why do we need to change this part of the policy?

_Because right now it might be used for kingsmaking_

> However, this makes strategies that depend on multiple turns or combat phases vulnerable to an **arranged** concession deal in order to potentially **kingmake** a player in order to force a draw. It's an edge case but it can definitely be something that can happen in high level play.

Well, if it is collusion and/or kingmaking, we'll penalize it as such. These will be ever easier to identify than regular "Board is confusing, he did this that sort of / kind of looks like a spite play or something, not sure".

With all of this I just mean to say that I'm not sure we are not covered by the rules already. It either is a regular situation and our policy works fine, or it isn't and we just move on to a different infraction

Excited to hear what everyone else has to say!

**Comment by fbatista** [comment]
> I very much dislike treating conceding as a Match Loss at a base level. Philosophically, it just does not make sense. We can talk about doing it with ill intent and getting into collusion situations, but the base mindset behind conceding cannot be that it is a very negative thing. By saying it is Unsporting Conduct - Major to concede at instant speed, we are saying it is as bad as, for example: A player using a racial slur against their opponent or a player taking inappropriate photos of another player without express permission (all examples from the IPG btw). If a player calls us and says "Listen, my wife is giving birth, I need to leave RIGHT NOW" or "I'm not feeling well, I need to go to the bathroom RIGHT NOW", does it make sense to say "All right, but what you are doing is as bad as if you had just called that person over there the n-word, so I'm giving you a Match Loss for Unsporting Conduct - Major"? No, absolutely not.

Agreed, my proposal was more in line of considering the concession as a match loss in terms of match points, in the case the game ends in a draw.

> In fact, philosophically, and unless we change the policy to reflect this, it shouldn't be ANY sort of penalty. The policy says "encourage", not "mandates". I agree with this wording, conceding has to be a rightly-available right for any player.

Agreed, i believe that allowing the player to remove themselves from an uncomfortable situation is the best costumer service we can provide! Specially considering how hard it is to be a graceful loser sometimes!

> Also, notice how our fix is already better than the one used in the US: we always help the players navigate to the end of the phase. This will always have to include an empty stack at some point, even if it's just at the end of said phase. The US fix only waits for the stack to be empty, which will always take less time than the help we provide with our fix.

The problem with the current fix is that it doesn't really fix much at all, when it comes to strategies that win over the course of multiple phases etc. It only covers the very niche situation of someone potentially conceding in response to a dockside, to deny treasures. But any situation where a player's winning strategy depends on the presence of certain game pieces or a player in the game, are affected. 

> I like the fix we have as it represents a compromise between players and tournament officials: you want this player to stay until the end, but we have to let them go. We can't have a judge sit here and play out the rest of the match because it would be a logistical strain and the skill of the judge as a player would start to factor in much more. On top of that, the player also needs to take their cards with them! It just isn't feasible, sorry.

Agreed! I believe that we cannot have the judge cannot play the role of the puppetmaster when a player decides to abandon the match. As you mentioned, there are a lot of problems, and the worst of all is that there may be things the judge forgets that would affect the game state, and there can be things that the other players do that violate the principle of "a table with a judge watching cannot be at a disadvantage when compared to a table without a judge".

---

So let's re-think this for a bit...

We want to:

- Avoid a situation where players do an "instant-speed" spite-concession, with the purpose of hurting a specific opponent, while simultaneously hurting themselves.
- Avoid a situation where players colluded and do an "instant-speed" concession, with the purpose of hurting one or more opponents, while simultaneously benefiting one or more opponents and hurting themselves.
- Avoid a situation where players use an "instant-speed" concession, with the purpose of forcing a draw, hurting one or more opponent's and simultaneously benefitting themselves and others.
- Allow a situation where players want to remove themselves from the game, at any time, because they feel the have no chance of winning the game anymore, or they are tired of playing, feeling like they are suffering by being forced to play the rest of the game, etc, but they still might want to continue playing the rest of the event!

We can't:
- Have the judge play on behalf of a player that left, or otherwise attempt to maintain the game state, since this is a pitfall where lots of problems can arise from.
 
How can we achieve ALL OF the above?

**Comment by JimmyLang420** [comment]
Instant speed concession = drop from tourney, without being able to re entry.

it fixes all of the above, except - wanting to leave game, because player is in a weird kingmaking position, in that case the player only needs to wait until his main phase and "thought it out"

same thing applies to  - Allow a situation where players want to remove themselves from the game, at any time, because they feel the have no chance of winning the game anymore, or they are tired of playing, feeling like they are suffering by being forced to play the rest of the game, etc, but they still might want to continue playing the rest of the event!

if player is too tired, then next round wont be much diferent, forcing a drop wouldnt be perfect but fixes most things on the list!

**Comment by fbatista** [comment]
> Instant speed concession = drop from tourney, without being able to re entry.
> 
> it fixes all of the above, except - wanting to leave game, because player is in a weird kingmaking position, in that case the player only needs to wait until his main phase and "thought it out"
> 
> same thing applies to - Allow a situation where players want to remove themselves from the game, at any time, because they feel the have no chance of winning the game anymore, or they are tired of playing, feeling like they are suffering by being forced to play the rest of the game, etc, but they still might want to continue playing the rest of the event!
> 
> if player is too tired, then next round wont be much diferent, forcing a drop wouldnt be perfect but fixes most things on the list!

A situation just came up with a high profile player, https://twitter-thread.com/t/1774197881496342862 , and although this seems like an edge case, it kind of pushes yet another problem into the table.

So instead of just "Instant speed concession = drop from the tournament", it needs to also disallow concessions while under control of an opponent.

**Comment by purplejudge** [comment]
> Instant speed concession = drop from tourney, without being able to re entry

I don't love this, because you might actually just need to concede for this round, but I suppose it is a fair compromise. If you have a non-severe emergency, you can always ask for 10 minutes and then get the time extension. This does open up an interesting debate however, since a player well-versed in the rules can ask for the 10 minutes, not come back, take the match loss, and continue in the tournament. Is this something we wish to allow?

> A situation just came up with a high profile player, https://twitter-thread.com/t/1774197881496342862 , and although this seems like an edge case, it kind of pushes yet another problem into the table.

I quite liked this scenario, since it is very reminiscent of the "I'm not kingmaking, this is better for me in the overall tournament". Sam Black made the correct play for him: concede now and hope for a draw, not allowing your opponent to win. One point is better than zero. This begs the question: is this something we wish to prevent? I read some of the comments saying "This is not real cEDH", but I don't know that I agree. It is morally grey, sure, but it ties back to the whole "Non-sporting is not unsporting". This is Competitive REL, he made the best competitive choice and tried to prevent someone from securing the win. Very interesting question, Fábio, great find!

**Comment by fbatista** [comment]
> This does open up an interesting debate however, since a player well-versed in the rules can ask for the 10 minutes, not come back, take the match loss, and continue in the tournament. Is this something we wish to allow?

In this case, that player would be lying to a tournament official, and therefore be disqualified ?

**Comment by purplejudge** [comment]
> In this case, that player would be lying to a tournament official, and therefore be disqualified ?

I can see what you mean, but this is not necessarily the case. Picture this:

I have to go to the bathroom, something I ate during lunch was probably spoiled. I don't know how long it'll take, but I know it won't be fast. Normally, I would just concede and be done with it, as I think I'll be okay for the next round. However, I know that if I concede now I'll be dropped from the tournament, so I'll ask for the 10 minutes and take my chances. It doesn't work out in my favor, I take 20 minutes to get back, so when I do, the game has progressed without me. The judge hands me my match loss and I'll go look at the vendors in the meantime.

Perhaps we can go shuffle these rules around and consider instant-speed concessions for what they might be: spite-plays. If we deem one to be such, it is treated as such. If the player can explain why conceding at that moment is the optimal play for them and their tournament run, then we should allow it. So, my proposal would be something like:

- **Incentivize** players to concede at sorcery speed (note that this is not what is currently in the rules, it just mentions "your turn, empty stack")
- They can, however, concede whenever they want, provided this concession doesn't directly affect the game being played after they leave.
- If it does, the situation must be considered further by the judge team, to see if there's potential for it to be considered a spite play. If there isn't, and the player can explain their reasoning for leaving right now, they're allowed to do so.
- Finally, regular cheating for lying to a tournament official applies (if they are conceding every round at suspicious moments because they have random emergencies, we'll have to look into it further)

**Comment by fbatista** [comment]
I like your proposal @purplejudge 

What about the penalty for spite play? USC Minor? Major?

What if the "spite play" actually benefits the player conceding, since it increases the chance the game ends in a draw, for example?

**Comment by purplejudge** [comment]
I just noticed I never replied to this, sorry! :(

I am torn between USC Minor and USC Major. I see pros and cons in both. I think it philosophically fits better in USC Minor, but it would not do much good as a Warning. Additionally, if someone is conceding specifically to "hurt" someone, it does feel like you could see it as "reasonably be expected to create a feeling of being **harassed**, threatened, bullied, or stalked.". I don't fully love it, but I do think it would be a fair compromise.

We would group up everything that qualifies as a spite play and/or kingmaking in examples for USC - Major. If it does fall into one of those categories, we just treat it as such: Match Loss. The philosophy of having to show remorse also works well here, so I like it. If we apply it during a concession, the Match Loss is applied in the next match (which is something the IPG allows).

> What if the "spite play" actually benefits the player conceding, since it increases the chance the game ends in a draw, for example?

As for this question, I think we apply the same logic we have so far: if it benefits you in any way (or you believe it does and can explain your reasoning to the judge), you are allowed to do it. We apply this logic to kingmaking, I don't see why we shouldn't apply it here. If you losing/drawing is better for me (e.g., because you are just behind me in standings, so you drawing / losing is enough for me to make top16), and I'm operating within the Magic rules, why should I have to help you beat me? **I shouldn't**.

Again, players **know** they are playing a multiplayer tournament. They knew this was the format the moment they signed up to play. They know these situations can happen when they are facing three opponents instead of one. That's just how the cookie crumbles sometimes. Yes, we will prevent people from being disruptive for the sake of being disruptive. However, if they only have their best interest in mind and don't break any rules, we do not and should not caution them. They are trying to win a **competitive** tournament. That's the whole point of a competitive tournament.

**Comment by fbatista** [comment]
I like this approach! I'm going to write it up and see where we end up :)
