### ISSUE TITLE
Revise IPG fixes involving fixes with opponent's choices

### ISSUE THREAD

**Issue by fbatista** [Juizes-MTG-Portugal/Juizes-MTG-Portugal.github.io#18]
As the metagame evolves and players understand the power of forging alliances mid-game to try to draw out the match, these fixes where a player makes a mistake and opponents get to choose what happens, have a huge potential to benefit the player that actually made an error.

As such, we should find a solution that doesn't have a chance to grant a benefit to the player that made a mistake.

The reason why in 1v1 this works, is because the opponent will ALWAYS want the worst outcome for the player that made the mistake, whereas in 4 FFA, there can be a situation where 1 player wants the worst outcome and 2 other players want the best outcome.

In light of the current version, the situation above will always result in the best outcome since 2 > 1. 

Also, keep in mind that these alliances are NOT collusion, because the players are simply trying to stop a win.

---
## Proposal

2.1A. Additional Remedy In Multiplayer Tournaments, since there are multiple opponents, the decisions that would be made by “the opponent” (when and if the missed trigger is put on the stack / resolves), are instead made through **a vote by the opponents of the offending Player. If no unanimous decision is reached, the final decision will be made by an chosen opponent chosen by the Head Judge. The criteria for which opponent is chosen should be based on the current game state, trying to pick an opponent with an intent diverging from the offending player's.**

2.3A Additional Remedy In Multiplayer Tournaments, the decision on what cards must be returned is made through **a vote by the Opponents of the offending Player. If no unanimous decision is reached, the final decision will be made by an opponent chosen by the Head Judge. The criteria for which opponent is chosen should be based on the current game state, trying to pick an opponent with an intent diverging from the offending player's.**

3.5A. Additional Remedy In Multiplayer Tournaments, the located card or cards are revealed to all opponents. The opponents must come to **a democratic decision on whether to fix the problem now or when a player would next get priority, and which missing cards replaces each incorrect card. If no unanimous decision is reached, the final decision will be made by an opponent chosen by the Head Judge. The criteria for which opponent is chosen should be based on the current game state, trying to pick an opponent with an intent diverging from the offending player's.**

**Comment by purplejudge** [comment]
I think we discussed this before, and I don't particularly like this change. Giving even more tasks to the Head Judge is dangerous, especially when we are talking about essentially **every GPE fix**. Seeing as statistically speaking it is easier for players to disagree than to agree on the decision, the HJ would be walking around settling disputes about such infractions the entire time. I would say that at the very least this proposal would have to be changed to "the judge" instead of "the Head Judge". Additionally, we need to be careful when including "current game state evaluation" in these fixes...

I don't dislike leaving the fix as it is currently, allowing for the majority to decide. This is multiplayer after all, and the players know going in that there will be times where the rest of the table will go against them and there's nothing they can do to change that. If this were an alliance or a deal struck during regular gameplay, we would not rule against it. Why do we draw the line here?

**Comment by fbatista** [comment]
Ultimately the problem is more relevant when the player that made the mistake is gaining a significant advantage from it. In this situation, judges are already going to be investigating deeper for cheating, and as such the problem kind of is already covered with that.

As such, maybe instead of adding such a strong policy change, instead we add some recommendation for investigating situations where the cheating might be a possibility, and mention this particular case as something to be on the lookout for?

What do you think?

**Comment by fbatista** [comment]
Resolved in: https://github.com/Juizes-MTG-Portugal/Juizes-MTG-Portugal.github.io/commit/af7334ea40ff9f22217e1125f960b2bc5852083a
