### ISSUE TITLE
Intentional Draws in Single Elimination

### ISSUE THREAD

**Issue by fbatista** [Juizes-MTG-Portugal/Juizes-MTG-Portugal.github.io#4]
Discuss and brainstorm solutions for the Intentional Draw situation in Single Elimination Rounds.

Inspiration: https://www.reddit.com/r/CompetitiveEDH/comments/17zu9g2/i_won_the_biggest_cedh_event_in_europe_the_pirate/

**Comment by JimmyLang420** [comment]
I belive the current system is the fairest as it is. *no timer, until first ID, then activating the invisible clock, for future games*
Some players dislike the end result being decided by standings, instead of game wins, then we will have to move away from being able to ID on the finals.
i know IDs are a tool in place to get out of undesirable boardstates, to decide who wins and who loses, but it should not be used in the current way. More often than id like to see, its being used to get out of boards where nobody payed for the taxes *remora,rhystics,etc*.
if we do move away from IDs, then we would be able to have a free timer type of thing on CEDH finals. 
if we keep the IDs and still want to have a no timer on finals type of thing, then the last thing we can do is rely on judges to be extremely heavy on Slow Play rulings, leading to many gamelosses.
either one of the options isnt a very good one in my opinion!
im open to other suggestions, lets keep the conversation going :D

Jimmy L

**Comment by FranciscoBarata21** [comment]
I also think the current system (no timer until first ID, then activating the invisible clock for future games) is fair enough, however i think the clock's time needs to be larger by 40 or 50 more minutes in order to avoid so many of these situations being decided by the standings. With this longer period of time to finish the final, i believe the option to restart a game will be more often realistically a good call than it is currently and in some scenarios it even gives an opportunity to restart the game twice (2 IDs) and if by that point the game is decided by standings it will at least be a bit more fair to the players since they got plenty of time to have played a second game.

**Comment by fbatista** [comment]
Current rules:

- No limitation

Current state-of-the-art:

- 120 minutes time limit start counting from the beginning of round;
- 120 minutes time limit only applies AFTER the first ID.
- After the time ends, the player with highest standings from swiss rounds wins.

## Proposals:

Idea A: ❤️ 
- Increase 120 to 150 minutes.

---

Idea B: 😄 
- Don't have a retroactive timer, and after the first ID apply the same timer process as during the swiss rounds.

---

Idea C: 🎉 
- Only allow for a single ID and after that allow for the game to continue without a time limit.

**Comment by purplejudge** [comment]
I like the solution we currently have, it forces players to _consider_ IDing, not assume it's where the natural progression of the game will take them every time. They must consider whether or not they have time to ID, because that means they still have to play an entirely new game after this one.

While I don't love increasing the time (because it opens the precedent that we'll just do it whenever we have a situation where the players ID and then the timer runs out), I think the increase to 150 is good, because we have an explanation for that number, as discussed with Fábio previously. Round is 90 minutes, so if we assume you take that long to play the first game, get to a drawing position, and then move on to a second game knowing your opponents' decks and that you have limited time, it makes sense you would then play faster. Not "30-minute-game" faster, but I think "60-minute-game" faster is fair.

I don't like the "allow a single ID" solution because it can create much larger issues, even though they might be rarer. If players know they can ID once whenever they want, we open the door to situations where they play a two, or three-hour game, ID, and then do it again. Yes, they might play a three-hour game with the current rules, but then they know they cannot ID and play a second game.

Additionally, and for your consideration, I think it would make sense to allow players to continue their post-ID games either until the timer runs out **or until the last table in that portion of the event finishes their match.** What I mean by this is that it doesn't make sense for players to ID, see the timer run out, pack their things, and then wait for 30 minutes because one of the other semifinals is, in fact, a two-hour game. They could have been playing for that time, perhaps even found a winner. I dislike that the ending of such games would be very abrupt (you're just waiting for someone across the hall to scream that the last semifinal is over), but I think it makes more sense than telling players to finish their match because we don't have infinite time and the venue needs to close at some point, and then tell them to wait 30+ minutes for the other matches to finish. Maybe y'all have some thoughts on how to implement this in a better way?

**Comment by fbatista** [comment]
I love this proposal of:

150 minutes retroactive limit after the first ID + extension until there are no other pods in this extension period still playing.

---

# Implementation

In the situation where players **Intentionally Draw a game in a Single Elimination Match**, it is recommended to apply the following restrictions:

* A 150 minutes timer that starts counting since the beginning of the Round comes into effect after the first Intentional Draw.
* After these 150 minutes, this Pod is allowed to continue playing, on _overtime_, as long as there other Pods still playing, not yet on _overtime_.
* After the 150 minutes + _overtime_ period is over, the match follows the standard End-of-Round procedure for the Tournament.
* In case the Match results in a Draw, the Player with the highest Standing from the Swiss Portion of the event should be considered the Winner.
* It is recommended that the Finals do not impose any time limit, even after Intentional Draws.

_**Example**:_

_During a Tournament Semifinals, Pod 1 is playing a 3-hour long grindy game. Pod 2 decided to Intentionally Draw a game at the 90 minute mark, hence triggering the 150 minutes timer, thus now having 60 minutes to reach a Match conclusion. After the 150 minutes have passed, they were made aware the Pod 1 is still playing and as such they are allowed overtime to continue playing, but that at any moment the Pod 1 finishes their match, they will have to wrap it up with the standard End-of-Round procedure for the event. As such, they had the chance to play for up to 30 minutes overtime and find a Winner through playing a game of Magic. After Pod 1 finishes their Match, and Pod 2 finishes the End-of-Round procedure, if no Winner is found, then the player with the highest standing from Swiss Rounds in Pod 2 is considered the Winner and moves on to the Finals._

**Comment by purplejudge** [comment]
Looks like a good implementation, easy to understand as well! Good job!
